#!/usr/bin/env python3
"""Builds index.html from hub-copy.json. All words live in the JSON; layout lives here and in hub.css.
Run: python3 build-hub.py   (no installs needed). Each text gets a non-breaking space before its
last word so a block can never end with one word alone."""
import json, html, pathlib
root = pathlib.Path(__file__).parent
c = json.loads((root / "hub-copy.json").read_text())

def t(s):
    s = html.escape(s, quote=False)
    i = s.rfind(" ")
    return s if i < 0 else s[:i] + "&nbsp;" + s[i + 1:]
def a(s): return html.escape(s, quote=True)
def ext(h): return ' target="_blank" rel="noopener noreferrer"' if h.startswith("http") else ""

kinds = {"primary": "pb-primary", "money": "pb-money", "secondary": "pb-secondary"}
doors = "\n".join(f'<a class="pb {kinds[d["kind"]]}" href="{a(d["href"])}"{ext(d["href"])}><span>{t(d["label"])}</span></a>' for d in c["doors"]["items"])
online = "\n".join(f'<a class="pb pb-secondary pb-two" href="{a(d["href"])}"{ext(d["href"])}><span>{t(d["label"])}</span><small>{t(d["who"])}</small></a>' for d in c["online"]["items"])
flinks = "\n".join(f'<a href="{a(d["href"])}"{ext(d["href"])}>{t(d["label"])}</a>' for d in c["footer"]["links"])
h = c["hero"]; ab = c["about"]

page = f'''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{html.escape(c["title"])}</title>
<meta name="description" content="{a(c["description"])}">
<meta name="color-scheme" content="dark">
<meta property="og:image" content="https://www.pacsarcade.com/assets/pacsarcde-banner-og.png">
<link rel="stylesheet" href="hub.css">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;800&display=swap" rel="stylesheet">
</head>
<body>
<!-- GENERATED by build-hub.py from hub-copy.json. Edit the JSON, not this file. -->
<header class="top"><div class="bar">
<a class="mark" href="/"><img src="assets/bitcoin.gif" alt="" width="24" height="24"><span>{t(c["wordmark"])}</span></a>
</div></header>
<div class="strip-wrap"><a id="bft-strip-clock" href="https://pacsarcade.org/time" data-caption="{a(c["clock_caption"])}" title="Bitcoin Federated Time: the clock that syncs to the block, not the sun. Open the time page."></a></div>
<main>
<section class="hero"><div class="panel hero-card">
<p class="kicker kicker-pink">{t(h["kicker"])}</p>
<h1 class="px">{t(h["title"])}</h1>
<p class="promise">{t(h["promise"])}</p>
<p class="line">{t(h["body"])}</p>
</div></section>
<section class="block"><div class="col">
<h2 class="px cyan">{t(c["doors"]["heading"])}</h2>
<div class="list">
{doors}
</div></div></section>
<section class="block"><div class="col">
<h2 class="px pink">{t(c["online"]["heading"])}</h2>
<div class="list">
{online}
</div></div></section>
<section class="block" id="about"><div class="col"><div class="panel about">
<h2 class="px pink">{t(ab["heading"])}</h2>
<p class="name px cyan">{t(ab["name"])}</p>
<p class="role px">{t(ab["role"])}</p>
<p class="body">{t(ab["text"])}</p>
<p class="more"><a href="{a(ab["more"]["href"])}"{ext(ab["more"]["href"])}>{t(ab["more"]["label"])}</a></p>
</div></div></section>
</main>
<footer class="foot"><div class="col">
<nav class="flinks" aria-label="Footer">
{flinks}
</nav>
<p class="legal">{t(c["footer"]["line"])}</p>
</div></footer>
<link rel="stylesheet" href="strip-clock.css">
<script src="strip-clock.js" defer></script>
</body>
</html>
'''
(root / "index.html").write_text(page)
print("wrote index.html", len(page), "bytes")
